### ISSUE TITLE
Does not work with webarchive files on any Mac system

### ISSUE THREAD

**Issue by eyelessjerry** [robrohan/WebArchiveExtractor#15]
Does not work with webarchive files on any Mac system (at least not on macOS Mojave and macOS Sequoia) – tested with a few examples and nothing at all happens when a file is dropped on the software that is sold.

**Comment by robrohan** [comment]
Hi eyelessjerry,I have had some reports of this on newer Macs. I think something with the file system permissions changed or something. If the app icon when you start it looks askew that is a tell tale sign something is odd. Seems to only be with newer Mx Mac’s. If you respond to the receipt email I’ll refund your purchase. Sent from the futureOn Oct 15, 2024, at 8:54 AM, eyelessjerry ***@***.***> wrote:﻿
Does not work with webarchive files on any Mac system (at least not on macOS Mojave and macOS Sequoia) – tested with a few examples and nothing at all happens when a file is dropped on the software that is sold.

**Comment by eyelessjerry** [comment]
Ok, thanks! Anyway macOS Mojave was on my old Intel MBP and Sequoia on my newer M2 MBA. See screen dump testing with my own "very" traditional website (was hoping to get some help moving a WiX website, but those are not easy to move in any way and guess that is the point from the hosting service, so ended up setting it up from scratch, but when it does not work with just plain html files uploaded through ftp ... .
<img width="1110" alt="screen 2024-10-15 kl  11 25 44" src="https://github.com/user-attachments/assets/8963a5ae-43db-412d-a9ce-24d2d3001419">

**Comment by robrohan** [comment]
Hi @eyelessjerry et al,

This was / is due to changes in the way macos sandboxes applications now. I've slightly updated the app (v 0.9.5) to be able to extract archives if they are located in your Downloads folder.  If you still have the link from the purchase, you can used the same link to download the latest version (the icon is still wonky on M1, M2, M3 macs for some awesome reason).

It's not clear how to fix this for any folder right off the bat, but moving the .webarchive file to the Downloads folder before dropping it into the extract window should work as a workaround.

**Comment by eyelessjerry** [comment]
I found the link in the history ... . It now works fine actually. The WiX website was not much helped by it, but it did download the images buried deep in nested folders and even the fonts ... (woff2 fonts that I do not know much about and not sure I can use at the similar place I put it up at – only option was to download Google fonts there). My own site I tested with where I don't use "advanced" coding was downloaded about as well as if I had done it through an FTP client. So now the app can be sold again :-).
